name: DebianContribution CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project's dependencies

    - name: Install pylint
      run: |
        pip install pylint

    - name: Run tests
      run: |
        python -m unittest discover -s . -p 'https://github.com/Razeetech/debianContribution/blob/main/test_debianCOntribution.py'
        # Specify the correct directory (-s) and test pattern (-p)

    - name: Lint code
      run: |
        pylint ./debianContribution.py

    env:
      PAT_TOKEN: ${{ secrets.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}}
